a
Ahn-seokjoo/android-weather-app pull request #5
Opened 2021-05-19 17:57 UTC by Ahn-seokjoo

a

2021-05-19 18:24 UTC, chuuuul requested changes
사용하지 않는 클래스 및 변수의 정리가 필요하고 MVVM 패턴에 대한 이해가 더 필요 할 것 같습니다.

2021-05-19 18:24 UTC, chuuuul commented on app/src/main/java/com/example/weatherapp/adapter/CityAdapter.kt
> +    override fun getItemCount(): Int = 1
사용하지 않는 변수는 지워주세요

2021-05-19 18:24 UTC, chuuuul commented on app/src/main/java/com/example/weatherapp/adapter/WeatherAdapter.kt
> +    override fun onBindViewHolder(holder: WeatherViewHolder, position: Int) {
onBindViewHolder 함수에서는 ViewHolder에 bind만 시켜주고 로직은 ViewHolder에 작성하면 깔끔할것 같습니다

```
// WeatherAdapter.kt
override fun onBindViewHolder(holder: WeatherViewHolder, position: Int) {
    holder.bind(getItem(position))
}

// WeatherViewHolder.kt
fun onBind(item : WeatherResult.WeatherResponse){
     // bind로직
}

```

2021-05-19 18:24 UTC, chuuuul commented on app/src/main/java/com/example/weatherapp/data/WeatherData.kt
> +    var min_temp: Int
해당 Data Class는 사용하지 않고 있는것 같습니다. 사용할거라면 Response 받은 데이터를 변환시키는 작업이 빠진 것 같습니다.

사용할거라면 불변변수로 변경해서 사용하고 Snake Naming 컨벤션을 사용하는것을 권장드립니다.

2021-05-19 18:24 UTC, chuuuul commented on app/src/main/java/com/example/weatherapp/main/view/MainFragment.kt
> +            seoulWeatherAdapter.submitList(viewModel.weatherRepo.getWeatherAsync(SEOUL))
ViewModel에 있는 Repository를 직접 접근해서 사용하고 있는데, ViewModel에 대한 이해가 필요 한 것 같습니다.

2021-05-19 18:24 UTC, chuuuul commented on app/src/main/java/com/example/weatherapp/main/viewmodel/WeatherViewModel.kt
> +    val weatherRepo = WeatherRepository()
MemoryWeatherRepository의 필요성이 모호한것 같습니다. 로컬에 데이터를 캐싱하거나 메모리에 갖고 있는것은 ViewModel에서 갖고 있어도 괜찮을 것 같습니다.

watherRepo는 다른곳에서 접근이 불가능하도록 private로 scope를 변경하는것이 좋을 것 같습니다.

2021-05-19 18:24 UTC, chuuuul commented on app/src/main/java/com/example/weatherapp/main/viewmodel/WeatherViewModel.kt
> +        _weatherListLiveData.value = repository.weatherList
사용하고 있지 않는 함수입니다.

2021-05-19 18:24 UTC, chuuuul commented on app/src/main/java/com/example/weatherapp/repository/WeatherResult.kt
> +    )
불변데이터 및 카멜케이스를 쓰는것을 권장드립니다.

2021-05-19 18:24 UTC, chuuuul commented on app/src/main/java/com/example/weatherapp/util/DateUtils.kt
> +object DateUtils {
사용하지 않는 클래스는 삭제하는것이 좋아보입니다.

2021-05-19 18:37 UTC, chuuuul requested changes

2021-05-19 18:37 UTC, chuuuul commented on app/src/main/java/com/example/weatherapp/main/view/MainFragment.kt
> +        _binding = FragmentMainBinding.inflate(inflater, container, false)
onCreateView에서는 binding만 정의해주고 나머지 View를 초기화하는부분은 onViewCreated에서 하는것이 좋을 것 같습니다.

2021-05-19 18:37 UTC, chuuuul commented on app/src/main/java/com/example/weatherapp/adapter/CityAdapter.kt
> +    class CityViewHolder(val binding: ItemCityNameBinding) : RecyclerView.ViewHolder(binding.root)
WeatherViewHolder가 분리되었다면 CityViewHolder도 분리하는것이 깔끔할 것 같습니다.

2021-05-19 18:37 UTC, chuuuul commented on app/src/main/java/com/example/weatherapp/adapter/WeatherAdapter.kt
> +            minTemp.text = result.min_temp.toInt().toString() + "℃"
문자열을 붙일때는 "" 안에 $을 사용하면 문자열 안에 변수를 넣을 수 있습니다.

2021-05-19 18:37 UTC, chuuuul commented on app/src/main/java/com/example/weatherapp/main/view/MainFragment.kt
> +            val londonTitleList = CityAdapter("London")
변수명이 List로 되어있는데 수정하면 좋을것 같습니다.

해당 방법처럼 Adapter를 여러개 만들어도 되지만 ViewType을 지정해서 Adapter하나로 구현하는 방법도 있습니다. 고려해보는것도 도움이 될 것 같습니다.

2021-05-19 19:56 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/adapter/WeatherAdapter.kt
> +            minTemp.text = result.min_temp.toInt().toString() + "℃"
with로 수정했습니다

2021-05-19 19:57 UTC, Ahn-seokjoo reviewed
with로 수정했습니다

2021-05-19 19:57 UTC, Ahn-seokjoo commented
> with로 수정했습니다

2021-05-19 20:03 UTC, Ahn-seokjoo commented
> with로 수정했습니다

2021-05-19 20:03 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/adapter/WeatherAdapter.kt
> +            minTemp.text = result.min_temp.toInt().toString() + "℃"
with

2021-05-19 20:08 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/adapter/WeatherAdapter.kt
> +            minTemp.text = result.min_temp.toInt().toString() + "℃"
> 문자열을 붙일때는 "" 안에 $을 사용하면 문자열 안에 변수를 넣을 수 있습니다.

with

2021-05-19 20:15 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/adapter/WeatherAdapter.kt
> +            minTemp.text = result.min_temp.toInt().toString() + "℃"
https://github.com/Ahn-seokjoo/android-weather-app/pull/5/commits/70b348dbe02fe8b73973211bfae6d9071abd7892

2021-05-21 04:41 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/util/DateUtils.kt
> +object DateUtils {
https://github.com/Ahn-seokjoo/android-weather-app/pull/5/commits/d32b46f77b3ce57149d0df299d2f9c29ec169423
불필요 클래스 삭제 했습니다.

2021-05-21 04:47 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/repository/WeatherResult.kt
> +    )
https://github.com/Ahn-seokjoo/android-weather-app/pull/5/commits/923a57d1f640cb2b2daf9130b4486310db040636
불변 데이터, 카멜 케이스로 교체 했습니다.

2021-05-22 14:06 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/data/WeatherData.kt
> +    var min_temp: Int
https://github.com/Ahn-seokjoo/android-weather-app/pull/5/commits/4fc7e4e7d3d27d0ce945a11d1538ce55c122b1c6
미사용 클래스 삭제

2021-05-22 16:47 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/adapter/CityAdapter.kt
> +    class CityViewHolder(val binding: ItemCityNameBinding) : RecyclerView.ViewHolder(binding.root)
https://github.com/Ahn-seokjoo/android-weather-app/pull/5/commits/fa4adf10c26e4e78b94b2c37b14336982fe43b40
뷰홀더 분리했습니다

2021-05-22 18:36 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/main/view/MainFragment.kt
> +        _binding = FragmentMainBinding.inflate(inflater, container, false)
https://github.com/Ahn-seokjoo/android-weather-app/pull/5/commits/0abe3267a485bc36744e3f4b0de10b5305bb68b8
분리 했습니다.

2021-05-22 18:39 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/main/viewmodel/WeatherViewModel.kt
> +        _weatherListLiveData.value = repository.weatherList
제거 완료했습니다

2021-05-22 18:40 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/main/viewmodel/WeatherViewModel.kt
> +    val weatherRepo = WeatherRepository()
현재 구조로서는 불가능해 인지하고 추후에 수정하겠습니다.

2021-05-23 14:19 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/adapter/WeatherAdapter.kt
> +    override fun onBindViewHolder(holder: WeatherViewHolder, position: Int) {
https://github.com/Ahn-seokjoo/android-weather-app/commit/8bd5bd52847bccd9930f1361411054281fed5296
구조대로 수정했습니다

2021-05-23 14:20 UTC, Ahn-seokjoo commented on app/src/main/java/com/example/weatherapp/main/view/MainFragment.kt
> +            seoulWeatherAdapter.submitList(viewModel.weatherRepo.getWeatherAsync(SEOUL))
현재 구조로서는 수정이 불가능해 추후에 수정하겠습니다

2021-05-23 17:30 UTC, chuuuul approved these changes

2025-03-13 01:47 UTC, merged